# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "TACO lab"
title:              "TACO lab at Korea Institute of Science and Technology"
description:        "This is a page for TACO lab, we are theoretical neurosciece lab at Korea Institute of Science and Technology, South Korea"


# URL
url:                http://kordinglab.com
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "research"
    href:           "/research"
  - name:           "publications"
    href:           "/publication"
  - name:           "people"
    href:           "/people"
  - name:           "recruitment"
    href:           "/recruitment"


# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
